### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GrantMTG** [MikroElektronika/mikrosdk_click_v2#64] opened 2023-08-28 19:19 UTC
**Describe the bug**
Mistake in the documentation README.MD for for the AudioAmp click (the first one).

**To Reproduce**
Go to
https://github.com/MikroElektronika/mikrosdk_click_v2/tree/master/clicks/audioamp

**Expected behavior**
This board uses the LM48100 chip *not* the LM386. 

**Additional context**
This causes searches and readers to bypass this repository thinking it is for another chip.

**Comment by GrantMTG** [comment] 2023-08-28 19:21
The photo is correct, but the product page link is incorrect also. It should be:

https://www.mikroe.com/audioamp-click

**Comment by MarkoZiv** [comment] 2023-08-29 06:59
@GrantMTG thank you for reporting
@StefanFilipovic15 please check and upload changes

**Comment by StefanFilipovic15** [comment] 2023-09-08 12:57
The issue is resolved in the latest update. https://github.com/MikroElektronika/mikrosdk_click_v2/pull/65
Thank you for reporting.

**Closed by StefanFilipovic15** 2023-09-08 12:57 UTC
