### ISSUE TITLE
[ PWM Click Driver Issue]

### ISSUE THREAD

**Issue by Hhaddegm** [MikroElektronika/mikrosdk_click_v2#26] opened 2022-03-08 12:26 UTC
**Describe the bug**

Memory access violation in pwm_output_config function of pwm lib ( pwm click )

**To Reproduce**

run the example test of pwm click

**Expected behavior**

a strange behavior of the output channel they are activated to HIGH at the init 

**Screenshots**

in the function below , it try to access the 5 byte of the config arrary but this arrary has only 4 bytes 
 
void pwm_output_config ( pwm_t *ctx, uint8_t *config1 )
{
    uint8_t output_buff[ 1 ];

    if( config1[ 0 ] > 3 )
    {
        config1[ 0 ] = config1[0] % 3;
    }
    output_buff[ 0 ] = 0;
    output_buff[ 0 ] |= ( config1[0] & 0x03 );
    output_buff[ 0 ] |= ( config1[1] & 0x01 ) << 2;
    output_buff[ 0 ] |= ( config1[2] & 0x01 ) << 3;
    output_buff[ 0 ] |= ( config1[4] & 0x01 ) << 4;

    pwm_generic_write( ctx, PWM_MODE2_REG, output_buff, 1 );
}

solution:

void pwm_output_config ( pwm_t *ctx, uint8_t *config1 )
{
    uint8_t output_buff[ 1 ];

    if( config1[ 0 ] > 3 )
    {
        config1[ 0 ] = config1[0] % 3;
    }
    output_buff[ 0 ] = 0;
    output_buff[ 0 ] |= ( config1[0] & 0x03 );
    output_buff[ 0 ] |= ( config1[1] & 0x01 ) << 2;
    output_buff[ 0 ] |= ( config1[2] & 0x01 ) << 3;
    output_buff[ 0 ] |= ( config1[3] & 0x01 ) << 4;

    pwm_generic_write( ctx, PWM_MODE2_REG, output_buff, 1 );
}

**Information (please complete the following information):**
 - OS: Windows
 - SDK V2
 - Click PWM
 - STM32

**Comment by StrahinjaJacimovic** [comment] 2022-03-10 09:38
Hello,
Thank you for reporting this issue.

Could you please create a pull request to this project with the change you suggested.

We will then review it, test and merge.

For more information please consult the following [DOCUMENT](https://github.com/MikroElektronika/mikrosdk_click_v2/blob/master/CONTRIBUTING.md).

**Comment by StefanFilipovic15** [comment] 2023-03-29 11:41
The issue is resolved in the latest update. #38 
Thank you for reporting.

**Closed by StefanFilipovic15** 2023-03-29 11:41 UTC
