### ISSUE TITLE
BUCKBOOST4_REG_REF MSB and LSB swapped?

### ISSUE THREAD

**Issue by tkreyche** [MikroElektronika/mikrosdk_click_v2#102] opened 2024-06-05 23:31 UTC
In https://github.com/MikroElektronika/mikrosdk_click_v2/blob/master/clicks/buckboost4/lib_buckboost4/include/buckboost4.h

You have the following registers defined as

#define BUCKBOOST4_REG_REF_MSB                   0x00
#define BUCKBOOST4_REG_REF_LSB                   0x01

Looking through the datasheet https://download.mikroe.com/documents/datasheets/TPS55289_datasheet.pdf it appears that these are swapped and the LSB should be at 0x00 and MSB at 0x01.

The TI data sheet lists 7.6.1 REF Register (Address = 0h, 1h) and has them in order: Figure 7-15. REF_LSB followed by Figure 7-16. REF_MSB.

I haven't used your code, but implemented my own Python library and it behaves as expected with at LSB at 0x00 and MSB 0x01. I hesitate to bring this up at this late date because surely someone else would have noticed this by now, but the error seems pretty obvious. Perhaps I am mistaken, or your code uses the registers in some manner that makes it irrelevant. 

Upon reset, using LSB at 0x00 and MSB 0x01 the reset values are 0xD2 and 0x00. The datasheet shows 0x00 for MSB reset and 0xA4 for LSB, which is different from what I get. Somewhere I saw that the chip can be ordered with different reset values and I suspect that is the case here for the LSB.

Setting REF to 0x0780h and NTFB to 01 produces an output of 10v, exactly as spec'd in Table 7.8 in the data sheet.

**Comment by MarkoZiv** [comment] 2024-06-06 06:35
Hello @tkreyche
thank you for reporting, we will investigate and follow up here.
Assigning to @StefanFilipovic15

**Comment by StefanFilipovic15** [comment] 2024-06-07 09:52
Hello @tkreyche 
The issue is resolved in #103.
Thank you for reporting.

**Closed by StefanFilipovic15** 2024-06-07 09:52 UTC

**Comment by tkreyche** [comment] 2024-06-07 19:02
Your BUCKBOOST4 Click board is nicely implemented and saved me a great deal of time evaluating the TPS55289 IC, which it turns out is perfect for the application I have in mind. Thanks!
