### ISSUE TITLE
[BUG] value of tx_buf is never set in accel19_set_control

### ISSUE THREAD

**Issue by qmalvido** [MikroElektronika/mikrosdk_click_v2#34] opened 2022-10-03 10:27 UTC
**Describe the bug**
In the _accel19_set_control_ function of the **Accel19** API the value of _tx_buf_ is never set before being passed to the _accel19_generic_write_ function.
![Screenshot 2022-10-03 at 11 23 19](https://user-images.githubusercontent.com/31891517/193555458-27316d1f-ae5a-498b-8828-c58eb7fa505b.png)
**Package Version**
Latest.

**Comment by StefanFilipovic15** [comment] 2023-03-29 11:44
The issue is resolved in the latest update. #38 
Thank you for reporting.

**Closed by StefanFilipovic15** 2023-03-29 11:44 UTC
