### ISSUE TITLE
Conflicting return type for environment3 click function environment3_get_gas_resistance() [BUG]

### ISSUE THREAD

**Issue by RobertWCarey** [MikroElektronika/mikrosdk_click_v2#56] opened 2023-07-17 05:15 UTC
**Describe the bug**
The environment3_get_gas_resistance() function for the environment3 click has conflicting types.
The header file says it returns a `uint32_t` where as the source file says `float`. Looks like float is the 
correct one from reading the docs.

In `clicks/environment3/lib_environment3/include/environment3.h:726`

```
 * @return @li @c  2.0 - No new data.
 *         @li @c -1.0 - Error.
 *         @li - Gas resistance value in Ohms.
 * @note None.
 */
uint32_t environment3_get_gas_resistance ( environment3_t *ctx );
```

In `clicks/environment3/lib_environment3/src/environment3.c:599`

```
float environment3_get_gas_resistance ( environment3_t *ctx )
{
    int8_t error_check = environment3_get_data ( ctx );
    
    if ( ENVIRONMENT3_OK != error_check )
    {
```

**To Reproduce**
See above.

**Expected behavior**
The `.h` and `.c` files should have the same return type for the function.

**Screenshots**
NA

**Information (please complete the following information):**
 - OS: NA
 - SDK version: NA
 - Click package version: Repo commit `d22d8d4cf`
 - HW related to issue (board, MCU, etc.)

**Additional context**
NA

**Comment by MarkoZiv** [comment] 2023-07-17 06:37
@StefanFilipovic15 fix this and upload please

**Comment by StefanFilipovic15** [comment] 2023-07-21 13:13
The issue is resolved in the latest update. https://github.com/MikroElektronika/mikrosdk_click_v2/pull/57
Thank you for reporting.

**Closed by StefanFilipovic15** 2023-07-21 13:13 UTC
