### ISSUE TITLE
[BUG] ADC4 

### ISSUE THREAD

**Issue by victorserbu2709** [MikroElektronika/mikrosdk_click_v2#33] opened 2022-09-29 14:09 UTC
**Describe the bug**
ADC4 setup error

https://github.com/MikroElektronika/mikrosdk_click_v2/blob/master/clicks/adc4/lib/include/adc4.h#L185

Acording with https://www.analog.com/media/en/technical-documentation/data-sheets/AD7175-8.pdf, I think 
#define ADC4_CH_EN                   0x8001
should be replaced with 
#define ADC4_CH_EN                   0x8000

**Comment by StrahinjaJacimovic** [comment] 2022-09-29 15:50
Thank you for reporting the bug @victorserbu2709 

The issue has been assigned to the appropriate developer and will be dealt with in a timely fashion.

Could you confirm if you've actually tested this on hardware?

Regards,
Strahinja.

**Comment by StefanFilipovic15** [comment] 2023-03-29 11:42
The issue is resolved in the latest update. #38 
Thank you for reporting.

**Closed by StefanFilipovic15** 2023-03-29 11:42 UTC
