### ISSUE TITLE
[BUG] Type 'temp' is used uninitialized in this function/ Type 'temp' may be used uninitialized in this function in captouch2.c

### ISSUE THREAD

**Issue by silabs-ThanhNgo** [MikroElektronika/mikrosdk_click_v2#37] opened 2022-11-29 07:12 UTC
**Describe the bug**
Type 'temp' is used uninitialized in this function/ Type 'temp' may be used uninitialized in this function in captouch2.c

**To Reproduce**
Type 'temp' may be used uninitialized in this function [Line 288 - captouch2.c](https://github.com/MikroElektronika/mikrosdk_click_v2/blob/master/clicks/captouch2/lib/src/captouch2.c#L288)
Type 'temp' is used uninitialized in this function/ Type 'temp' may be used uninitialized in this function in captouch2.c : go to [Line 298 - captouch2.c](https://github.com/MikroElektronika/mikrosdk_click_v2/blob/master/clicks/captouch2/lib/src/captouch2.c#L298) and check the code

**Expected behavior**
All the warning are cleared to avoid malfunction

**Screenshots**
![image](https://user-images.githubusercontent.com/64764598/204438083-d5510554-fe14-4cba-a2bd-c0779f2bd4d1.png)

**Information (please complete the following information):**
NA

**Additional context**
NA

**Comment by StefanFilipovic15** [comment] 2023-03-29 11:45
The issue is resolved in the latest update. #38 
Thank you for reporting.

**Closed by StefanFilipovic15** 2023-03-29 11:45 UTC
